// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LXCCreateResponseSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        upid: {
            type: 'string',
            title: 'Upid'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'upid', 'message'],
    title: 'LXCCreateResponse',
    description: 'Response after creating LXC container.'
} as const;

export const LXCCreateSchemaSchema = {
    properties: {
        hostname: {
            type: 'string',
            title: 'Hostname'
        },
        ostemplate: {
            type: 'string',
            title: 'Ostemplate'
        },
        cores: {
            type: 'integer',
            title: 'Cores',
            default: 1
        },
        memory: {
            type: 'integer',
            title: 'Memory',
            default: 512
        },
        rootfs_size: {
            type: 'integer',
            title: 'Rootfs Size',
            default: 8
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        storage: {
            type: 'string',
            title: 'Storage',
            default: 'local-lvm'
        },
        environment_type: {
            type: 'string',
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        start: {
            type: 'boolean',
            title: 'Start',
            default: true
        },
        unprivileged: {
            type: 'boolean',
            title: 'Unprivileged',
            default: true
        }
    },
    type: 'object',
    required: ['hostname', 'ostemplate', 'password', 'environment_type'],
    title: 'LXCCreateSchema',
    description: 'Schema for creating a new LXC container.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: '通用訊息回應'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: '重設密碼請求'
} as const;

export const NodeSchemaSchema = {
    properties: {
        node: {
            type: 'string',
            title: 'Node'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime'
        }
    },
    type: 'object',
    required: ['node', 'status'],
    title: 'NodeSchema',
    description: 'Proxmox node information.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ResourcePublicSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        node: {
            type: 'string',
            title: 'Node'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        environment_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime'
        }
    },
    type: 'object',
    required: ['vmid', 'name', 'status', 'node', 'type'],
    title: 'ResourcePublic',
    description: '公開的資源資訊，合併Proxmox資料和資料庫額外資訊.'
} as const;

export const TemplateSchemaSchema = {
    properties: {
        volid: {
            type: 'string',
            title: 'Volid'
        },
        format: {
            type: 'string',
            title: 'Format'
        },
        size: {
            type: 'integer',
            title: 'Size'
        }
    },
    type: 'object',
    required: ['volid', 'format', 'size'],
    title: 'TemplateSchema',
    description: 'OS template information.'
} as const;

export const TerminalInfoSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        ws_url: {
            type: 'string',
            title: 'Ws Url'
        },
        ticket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'ws_url', 'message'],
    title: 'TerminalInfoSchema',
    description: 'Terminal console connection information for LXC containers.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JWT 存取權杖回應'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: '更新密碼請求'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: '建立使用者時接收的資料'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'API 回傳的使用者資料'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: '使用者自行註冊時使用的資料'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: '更新使用者時接收的資料'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: '使用者更新自己資料時使用'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'API 回傳的使用者列表'
} as const;

export const VMCreateResponseSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        upid: {
            type: 'string',
            title: 'Upid'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'upid', 'message'],
    title: 'VMCreateResponse',
    description: 'Response after creating VM.'
} as const;

export const VMCreateSchemaSchema = {
    properties: {
        hostname: {
            type: 'string',
            title: 'Hostname'
        },
        template_id: {
            type: 'integer',
            title: 'Template Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        cores: {
            type: 'integer',
            title: 'Cores',
            default: 2
        },
        memory: {
            type: 'integer',
            title: 'Memory',
            default: 2048
        },
        disk_size: {
            type: 'integer',
            title: 'Disk Size',
            default: 20
        },
        storage: {
            type: 'string',
            title: 'Storage',
            default: 'local-lvm'
        },
        environment_type: {
            type: 'string',
            title: 'Environment Type'
        },
        os_info: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os Info'
        },
        expiry_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expiry Date'
        },
        start: {
            type: 'boolean',
            title: 'Start',
            default: true
        }
    },
    type: 'object',
    required: ['hostname', 'template_id', 'username', 'password', 'environment_type'],
    title: 'VMCreateSchema',
    description: 'Schema for creating a new VM from cloud-init template.'
} as const;

export const VMSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        node: {
            type: 'string',
            title: 'Node'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        cpu: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu'
        },
        maxcpu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxcpu'
        },
        mem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mem'
        },
        maxmem: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxmem'
        },
        uptime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uptime'
        },
        netin: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netin'
        },
        diskread: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diskread'
        },
        diskwrite: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diskwrite'
        },
        disk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk'
        },
        template: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template'
        },
        memhost: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memhost'
        },
        maxdisk: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdisk'
        }
    },
    type: 'object',
    required: ['vmid', 'name', 'status', 'node', 'type'],
    title: 'VMSchema',
    description: 'Virtual machine information.'
} as const;

export const VMTemplateSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        node: {
            type: 'string',
            title: 'Node'
        }
    },
    type: 'object',
    required: ['vmid', 'name', 'node'],
    title: 'VMTemplateSchema',
    description: 'VM template information.'
} as const;

export const VNCInfoSchemaSchema = {
    properties: {
        vmid: {
            type: 'integer',
            title: 'Vmid'
        },
        ws_url: {
            type: 'string',
            title: 'Ws Url'
        },
        ticket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['vmid', 'ws_url', 'message'],
    title: 'VNCInfoSchema',
    description: 'VNC console connection information.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;