// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, LxcGetLxcTerminalData, LxcGetLxcTerminalResponse, LxcGetTemplatesResponse, LxcCreateLxcData, LxcCreateLxcResponse, PrivateCreateUserData, PrivateCreateUserResponse, ResourcesListNodesResponse, ResourcesListResourcesData, ResourcesListResourcesResponse, ResourcesListMyResourcesResponse, ResourcesGetResourceData, ResourcesGetResourceResponse, ResourcesDeleteResourceData, ResourcesDeleteResourceResponse, ResourcesGetResourceConfigData, ResourcesGetResourceConfigResponse, ResourcesStartResourceData, ResourcesStartResourceResponse, ResourcesStopResourceData, ResourcesStopResourceResponse, ResourcesRebootResourceData, ResourcesRebootResourceResponse, ResourcesShutdownResourceData, ResourcesShutdownResourceResponse, ResourcesResetResourceData, ResourcesResetResourceResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, VmGetVmConsoleData, VmGetVmConsoleResponse, VmCreateVmData, VmCreateVmResponse, VmGetVmTemplatesResponse, VmRequestsCreateData, VmRequestsCreateResponse, VmRequestsListMyData, VmRequestsListMyResponse, VmRequestsListAllData, VmRequestsListAllResponse, VmRequestsGetData, VmRequestsGetResponse, VmRequestsReviewData, VmRequestsReviewResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LxcService {
    /**
     * Get Lxc Terminal
     * @param data The data for the request.
     * @param data.vmid
     * @returns TerminalInfoSchema Successful Response
     * @throws ApiError
     */
    public static getLxcTerminal(data: LxcGetLxcTerminalData): CancelablePromise<LxcGetLxcTerminalResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/lxc/{vmid}/terminal',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Templates
     * Get available OS templates for LXC containers.
     * @returns TemplateSchema Successful Response
     * @throws ApiError
     */
    public static getTemplates(): CancelablePromise<LxcGetTemplatesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/lxc/templates'
        });
    }
    
    /**
     * Create Lxc
     * Create a new LXC container.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LXCCreateResponse Successful Response
     * @throws ApiError
     */
    public static createLxc(data: LxcCreateLxcData): CancelablePromise<LxcCreateLxcResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/lxc/create',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ResourcesService {
    /**
     * List Nodes
     * @returns NodeSchema Successful Response
     * @throws ApiError
     */
    public static listNodes(): CancelablePromise<ResourcesListNodesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/resources/nodes'
        });
    }
    
    /**
     * List Resources
     * @param data The data for the request.
     * @param data.node
     * @returns ResourcePublic Successful Response
     * @throws ApiError
     */
    public static listResources(data: ResourcesListResourcesData = {}): CancelablePromise<ResourcesListResourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/resources/',
            query: {
                node: data.node
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * List My Resources
     * List resources owned by the current user (approved VMs/containers).
     * @returns ResourcePublic Successful Response
     * @throws ApiError
     */
    public static listMyResources(): CancelablePromise<ResourcesListMyResourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/resources/my'
        });
    }
    
    /**
     * Get Resource
     * @param data The data for the request.
     * @param data.vmid
     * @returns VMSchema Successful Response
     * @throws ApiError
     */
    public static getResource(data: ResourcesGetResourceData): CancelablePromise<ResourcesGetResourceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/resources/{vmid}',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Resource
     * Delete a resource (VM or LXC container).
     *
     * Automatically detects resource type and performs appropriate deletion.
     *
     * Args:
     * vmid: Resource ID to delete
     * purge: Remove resource from all related configurations (default: True)
     * force: Force stop the resource if running (default: False)
     * @param data The data for the request.
     * @param data.vmid
     * @param data.purge
     * @param data.force
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteResource(data: ResourcesDeleteResourceData): CancelablePromise<ResourcesDeleteResourceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/resources/{vmid}',
            path: {
                vmid: data.vmid
            },
            query: {
                purge: data.purge,
                force: data.force
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Resource Config
     * @param data The data for the request.
     * @param data.vmid
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getResourceConfig(data: ResourcesGetResourceConfigData): CancelablePromise<ResourcesGetResourceConfigResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/resources/{vmid}/config',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Start Resource
     * @param data The data for the request.
     * @param data.vmid
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static startResource(data: ResourcesStartResourceData): CancelablePromise<ResourcesStartResourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/resources/{vmid}/start',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Stop Resource
     * @param data The data for the request.
     * @param data.vmid
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static stopResource(data: ResourcesStopResourceData): CancelablePromise<ResourcesStopResourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/resources/{vmid}/stop',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reboot Resource
     * @param data The data for the request.
     * @param data.vmid
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static rebootResource(data: ResourcesRebootResourceData): CancelablePromise<ResourcesRebootResourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/resources/{vmid}/reboot',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Shutdown Resource
     * @param data The data for the request.
     * @param data.vmid
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static shutdownResource(data: ResourcesShutdownResourceData): CancelablePromise<ResourcesShutdownResourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/resources/{vmid}/shutdown',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Resource
     * @param data The data for the request.
     * @param data.vmid
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static resetResource(data: ResourcesResetResourceData): CancelablePromise<ResourcesResetResourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/resources/{vmid}/reset',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class VmService {
    /**
     * Get Vm Console
     * @param data The data for the request.
     * @param data.vmid
     * @returns VNCInfoSchema Successful Response
     * @throws ApiError
     */
    public static getVmConsole(data: VmGetVmConsoleData): CancelablePromise<VmGetVmConsoleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vm/{vmid}/console',
            path: {
                vmid: data.vmid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Vm
     * Create a new VM from a cloud-init template.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns VMCreateResponse Successful Response
     * @throws ApiError
     */
    public static createVm(data: VmCreateVmData): CancelablePromise<VmCreateVmResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/vm/create',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Vm Templates
     * Get available VM templates (VMs marked as templates).
     * @returns VMTemplateSchema Successful Response
     * @throws ApiError
     */
    public static getVmTemplates(): CancelablePromise<VmGetVmTemplatesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vm/templates'
        });
    }
}

export class VmRequestsService {
    /**
     * Create VM Request
     * Submit a new VM/LXC request (requires reason).
     */
    public static createVmRequest(data: VmRequestsCreateData): CancelablePromise<VmRequestsCreateResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/vm-requests/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * List My VM Requests
     * List the current user's VM requests.
     */
    public static listMyVmRequests(data: VmRequestsListMyData = {}): CancelablePromise<VmRequestsListMyResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vm-requests/my',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * List All VM Requests (Admin)
     * List all VM requests.
     */
    public static listAllVmRequests(data: VmRequestsListAllData = {}): CancelablePromise<VmRequestsListAllResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vm-requests/',
            query: {
                status: data.status,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get VM Request
     * Get a single VM request.
     */
    public static getVmRequest(data: VmRequestsGetData): CancelablePromise<VmRequestsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vm-requests/{request_id}',
            path: {
                request_id: data.requestId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Review VM Request (Admin)
     * Approve or reject a VM request.
     */
    public static reviewVmRequest(data: VmRequestsReviewData): CancelablePromise<VmRequestsReviewResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/vm-requests/{request_id}/review',
            path: {
                request_id: data.requestId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}