// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 通用訊息回應
 */
export type Message = {
    message: string;
};

/**
 * 重設密碼請求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Proxmox node information.
 */
export type NodeSchema = {
    node: string;
    status: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Terminal console connection information for LXC containers.
 */
export type TerminalInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

/**
 * JWT 存取權杖回應
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 更新密碼請求
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 建立使用者時接收的資料
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * API 回傳的使用者資料
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 使用者自行註冊時使用的資料
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * API 回傳的使用者列表
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 更新使用者時接收的資料
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 使用者更新自己資料時使用
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Virtual machine information.
 */
export type VMSchema = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

/**
 * VNC console connection information.
 */
export type VNCInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MachineListNodesResponse = (Array<NodeSchema>);

export type MachineListVmsData = {
    node?: (string | null);
};

export type MachineListVmsResponse = (Array<VMSchema>);

export type MachineGetVmInfoData = {
    vmid: number;
};

export type MachineGetVmInfoResponse = (VMSchema);

export type MachineGetVmConsoleData = {
    vmid: number;
};

export type MachineGetVmConsoleResponse = (VNCInfoSchema);

export type MachineGetLxcTerminalData = {
    vmid: number;
};

export type MachineGetLxcTerminalResponse = (TerminalInfoSchema);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);