// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response after creating LXC container.
 */
export type LXCCreateResponse = {
    vmid: number;
    upid: string;
    message: string;
};

/**
 * Schema for creating a new LXC container.
 */
export type LXCCreateSchema = {
    hostname: string;
    ostemplate: string;
    cores?: number;
    memory?: number;
    rootfs_size?: number;
    password: string;
    storage?: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    start?: boolean;
    unprivileged?: boolean;
};

/**
 * 通用訊息回應
 */
export type Message = {
    message: string;
};

/**
 * 重設密碼請求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Proxmox node information.
 */
export type NodeSchema = {
    node: string;
    status: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 公開的資源資訊，合併Proxmox資料和資料庫額外資訊.
 */
export type ResourcePublic = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    environment_type?: (string | null);
    os_info?: (string | null);
    expiry_date?: (string | null);
    ip_address?: (string | null);
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
};

/**
 * OS template information.
 */
export type TemplateSchema = {
    volid: string;
    format: string;
    size: number;
};

/**
 * Terminal console connection information for LXC containers.
 */
export type TerminalInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

/**
 * JWT 存取權杖回應
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 更新密碼請求
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 建立使用者時接收的資料
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * API 回傳的使用者資料
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 使用者自行註冊時使用的資料
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * API 回傳的使用者列表
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 更新使用者時接收的資料
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 使用者更新自己資料時使用
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Response after creating VM.
 */
export type VMCreateResponse = {
    vmid: number;
    upid: string;
    message: string;
};

/**
 * Schema for creating a new VM from cloud-init template.
 */
export type VMCreateSchema = {
    hostname: string;
    template_id: number;
    username: string;
    password: string;
    cores?: number;
    memory?: number;
    disk_size?: number;
    storage?: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    start?: boolean;
};

/**
 * Virtual machine information.
 */
export type VMSchema = {
    vmid: number;
    name: string;
    status: string;
    node: string;
    type: string;
    cpu?: (number | null);
    maxcpu?: (number | null);
    mem?: (number | null);
    maxmem?: (number | null);
    uptime?: (number | null);
    netin?: (number | null);
    diskread?: (number | null);
    diskwrite?: (number | null);
    disk?: (number | null);
    template?: (number | null);
    memhost?: (number | null);
    maxdisk?: (number | null);
};

/**
 * VM template information.
 */
export type VMTemplateSchema = {
    vmid: number;
    name: string;
    node: string;
};

/**
 * VNC console connection information.
 */
export type VNCInfoSchema = {
    vmid: number;
    ws_url: string;
    ticket?: (string | null);
    message: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LxcGetLxcTerminalData = {
    vmid: number;
};

export type LxcGetLxcTerminalResponse = (TerminalInfoSchema);

export type LxcGetTemplatesResponse = (Array<TemplateSchema>);

export type LxcCreateLxcData = {
    requestBody: LXCCreateSchema;
};

export type LxcCreateLxcResponse = (LXCCreateResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResourcesListNodesResponse = (Array<NodeSchema>);

export type ResourcesListResourcesData = {
    node?: (string | null);
};

export type ResourcesListResourcesResponse = (Array<ResourcePublic>);

export type ResourcesListMyResourcesResponse = (Array<ResourcePublic>);

export type ResourcesGetResourceData = {
    vmid: number;
};

export type ResourcesGetResourceResponse = (VMSchema);

export type ResourcesDeleteResourceData = {
    force?: boolean;
    purge?: boolean;
    vmid: number;
};

export type ResourcesDeleteResourceResponse = (unknown);

export type ResourcesGetResourceConfigData = {
    vmid: number;
};

export type ResourcesGetResourceConfigResponse = (unknown);

export type ResourcesStartResourceData = {
    vmid: number;
};

export type ResourcesStartResourceResponse = (unknown);

export type ResourcesStopResourceData = {
    vmid: number;
};

export type ResourcesStopResourceResponse = (unknown);

export type ResourcesRebootResourceData = {
    vmid: number;
};

export type ResourcesRebootResourceResponse = (unknown);

export type ResourcesShutdownResourceData = {
    vmid: number;
};

export type ResourcesShutdownResourceResponse = (unknown);

export type ResourcesResetResourceData = {
    vmid: number;
};

export type ResourcesResetResourceResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type VmGetVmConsoleData = {
    vmid: number;
};

export type VmGetVmConsoleResponse = (VNCInfoSchema);

export type VmCreateVmData = {
    requestBody: VMCreateSchema;
};

export type VmCreateVmResponse = (VMCreateResponse);

export type VmGetVmTemplatesResponse = (Array<VMTemplateSchema>);

// ===== VM Request Types =====

export type VMRequestStatus = 'pending' | 'approved' | 'rejected';

/**
 * 建立虛擬機申請的 Schema.
 */
export type VMRequestCreate = {
    reason: string;
    resource_type: string;
    hostname: string;
    cores?: number;
    memory?: number;
    password: string;
    storage?: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    ostemplate?: (string | null);
    rootfs_size?: (number | null);
    template_id?: (number | null);
    disk_size?: (number | null);
    username?: (string | null);
};

/**
 * 審核虛擬機申請的 Schema.
 */
export type VMRequestReview = {
    status: VMRequestStatus;
    review_comment?: (string | null);
};

/**
 * 公開的虛擬機申請資訊.
 */
export type VMRequestPublic = {
    id: string;
    user_id: string;
    user_email?: (string | null);
    user_full_name?: (string | null);
    reason: string;
    resource_type: string;
    hostname: string;
    cores: number;
    memory: number;
    storage: string;
    environment_type: string;
    os_info?: (string | null);
    expiry_date?: (string | null);
    ostemplate?: (string | null);
    rootfs_size?: (number | null);
    template_id?: (number | null);
    disk_size?: (number | null);
    username?: (string | null);
    status: VMRequestStatus;
    reviewer_id?: (string | null);
    review_comment?: (string | null);
    reviewed_at?: (string | null);
    vmid?: (number | null);
    created_at: string;
};

/**
 * 虛擬機申請列表.
 */
export type VMRequestsPublic = {
    data: Array<VMRequestPublic>;
    count: number;
};

export type VmRequestsCreateData = {
    requestBody: VMRequestCreate;
};

export type VmRequestsCreateResponse = (VMRequestPublic);

export type VmRequestsListMyData = {
    skip?: number;
    limit?: number;
};

export type VmRequestsListMyResponse = (VMRequestsPublic);

export type VmRequestsListAllData = {
    status?: (VMRequestStatus | null);
    skip?: number;
    limit?: number;
};

export type VmRequestsListAllResponse = (VMRequestsPublic);

export type VmRequestsGetData = {
    requestId: string;
};

export type VmRequestsGetResponse = (VMRequestPublic);

export type VmRequestsReviewData = {
    requestId: string;
    requestBody: VMRequestReview;
};

export type VmRequestsReviewResponse = (VMRequestPublic);