"""Add vm_requests table

Revision ID: 883012a55f1e
Revises: a3b7c9d1e2f4
Create Date: 2026-02-22 21:31:25.533741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '883012a55f1e'
down_revision = 'a3b7c9d1e2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vm_requests_user_id_fkey'), 'vm_requests', type_='foreignkey')
    op.create_foreign_key(None, 'vm_requests', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vm_requests', type_='foreignkey')
    op.create_foreign_key(op.f('vm_requests_user_id_fkey'), 'vm_requests', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
